{
  imports = [
    ./atuin.nix
    ./awscli.nix
    ./browsers.nix
    ./btm.nix
    ./bun.nix
    ./claude-code.nix
    ./claude-desktop.nix
    ./coderabbit.nix
    ./direnv.nix
    ./datagrip.nix
    ./discord.nix
    ./eza.nix
    ./fzf.nix
    ./git.nix
    ./gpg.nix
    ./go-task.nix
    ./gtk.nix
    ./nixfmt.nix
    ./neovim.nix
    ./obsidian.nix
    ./onlyoffice.nix
    ./lazygit.nix
    ./opencode.nix
    ./sftp.nix
    ./slack.nix
    ./sops.nix
    ./spotify.nix
    ./ssh.nix
    ./starship.nix
    ./tealdeer.nix
    ./teams-for-linux.nix
    ./todoist.nix
    ./thunderbird.nix
    ./zsh.nix
    ./yazi.nix
    ./hyprland.nix
    ./foot.nix
    ./stylix.nix
    ./waybar.nix
    ./vicinae.nix
    ./zoxide.nix
  ];
}
