{
  imports = [
    ./browsers.nix
    ./btm.nix
    ./bun.nix
    ./datagrip.nix
    ./git.nix
    ./go-task.nix
    ./nixfmt.nix
    ./neovim.nix
    ./lazygit.nix
    ./opencode.nix
    ./teams-for-linux.nix
    ./thunderbird.nix
    ./zsh.nix
    ./yazi.nix
    ./hyprland.nix
    ./foot.nix
    ./waybar.nix
    ./vicinae.nix
  ];
}
