#!/usr/bin/env bash
# ---
# description: Download files from Presbyterian SFTP server
# ---

# Check if variables are set
if [[ -z "$PRES_SFTP_FROM_PATH" ]]; then
    echo "Error: Secrets not loaded."
    exit 1
fi

echo "Downloading files to: $(pwd)"

sftp presbyterian-prod <<EOF
cd "$PRES_SFTP_FROM_PATH"
get -r *
bye
EOF
